<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>ClanSystem</AssemblyName>
    <RootNamespace>ClanSystem</RootNamespace>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>
    <DebugType>pdbonly</DebugType>
    <Optimize Condition="'$(Configuration)' == 'Release'">true</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ExMod.Exiled" Version="9.14.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net48" Version="1.0.3" PrivateAssets="All" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="References\Unity.TextMeshPro\Unity.TextMeshPro.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>
</Project>
