<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>Unity.TextMeshPro</AssemblyName>
    <RootNamespace>TMPro</RootNamespace>
    <Product>Unity.TextMeshPro compile reference</Product>
    <Deterministic>true</Deterministic>
    <DebugType>pdbonly</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net48" Version="1.0.3" PrivateAssets="All" />
  </ItemGroup>
</Project>
